language: node_js
node_js: 12

services:
  - docker

install:
  - Xvfb :1 -screen 0 ${WINDOW_WIDTH}x${WINDOW_HEIGHT}x24 :1 -ac >& /dev/null &
  - ./tools/travis/microk8s.sh &
  - k8s=$!
  - npm ci
  - wait $k8s

# below, the various stages will define S and T
script: npm run test:$T $S

jobs:
  include:
    - stage: test
      env: S=k8s T=electron
    - stage: test
      env: S=k8s1 T=electron
    - stage: test
      env: S=k8s1 T=webpack
    - stage: test
      env: S=k8s2 T=electron
    - stage: test
      env: S=k8s2 T=webpack
    - stage: test
      env: S=helm T=electron NEEDS_HELM=true
    - stage: test
      env: S=helm T=webpack NEEDS_HELM=true
    - stage: release
      script: npm install -g release-it@12.4.3 && release-it
      if: tag =~ /^v([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/

env:
  global:
    - TRAVIS_KUBE_VERSION=1.12
    - TRAVIS_HELM_VERSION=2.13.0
    - WINDOW_WIDTH=1400
    - WINDOW_HEIGHT=1050
    - PATH=bin:$PATH
    - CSP_ALLOWED_HOSTS="https://raw.githubusercontent.com http://localhost:8081 ws://localhost:8081 http://localhost:9953 http://localhost:9080 ws://localhost:9080"
